[build]
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "18"

# www → apex (http + https)
[[redirects]]
  from = "http://www.jcsworld.in/*"
  to = "https://jcsworld.in/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.jcsworld.in/*"
  to = "https://jcsworld.in/:splat"
  status = 301
  force = true

# Cache rules
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/global.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
